name: 'Setup Maven certificates'
description: 'Setup certificate for maven to be able to access private repository'
inputs:
  maven-settings:
    description: 'Content of the maven configuration settings file in base64 format'
    required: true
  maven-security-settings:
    description: 'Content of the maven configuration security settings file in base64 format'
    required: true
  maven-p12-keystore:
    description: 'Base64 encoded content of p12 keystore file used for accessing the private remote maven repository'
    required: true
  maven-p12-keystore-password:
    description: 'Base64 encoded password to access the p12 maven keystore'
    required: true
  company-rootca:
    description: "Base64 encoded content of company's root CA certififcate"
    required: true
runs:
  using: "composite"
  steps:
    - id: setup-certificates
      shell: bash
      run: |
        echo "Configuring maven ..."
        echo "${{ inputs.maven-settings }}" | base64 -d > ${HOME}/.m2/settings.xml
        echo "${{ inputs.maven-security-settings }}" | base64 -d > ${HOME}/.m2/settings-security.xml
        mkdir ~/certs
        echo "${{ inputs.maven-p12-keystore }}" | base64 -d > ${HOME}/certs/certificate.p12
        echo "${{ inputs.company-rootca }}" | base64 -d > ${HOME}/certs/rootca.crt
        echo "export MAVEN_OPTS=\"-Djavax.net.ssl.keyStore=${HOME}/certs/certificate.p12 -Djavax.net.ssl.keyStoreType=pkcs12 -Djavax.net.ssl.keyStorePassword=${{ inputs.maven-p12-keystore-password }}\"" \
        >> ~/.mavenrc
        sudo ${JAVA_HOME}/bin/keytool -importcert -cacerts -storepass changeit -noprompt -alias mycert -file ~/certs/rootca.crt
